// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZzROqtKQQyB-w2gimCuF22AqPojudM2w',
    appId: '1:520286223732:web:ebab52e43928e1cac10021',
    messagingSenderId: '520286223732',
    projectId: 'spotify-24',
    authDomain: 'spotify-24.firebaseapp.com',
    storageBucket: 'spotify-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNIEQgFTc6RAANHS7JtKcT47_jdwMKE6Y',
<<<<<<< HEAD
    appId: '1:520286223732:android:5e4fca3b814423dac10021',
=======
    appId: '1:520286223732:android:81d7e384f8cbd8a0c10021',
>>>>>>> 14487d6fe0bb0d91463388cf6d7c3a1bc0562349
    messagingSenderId: '520286223732',
    projectId: 'spotify-24',
    storageBucket: 'spotify-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvcejycVPCUdHkEjyvk6nexSbgF3VDZ_k',
    appId: '1:520286223732:ios:7bcd95a2f472ded4c10021',
    messagingSenderId: '520286223732',
    projectId: 'spotify-24',
    storageBucket: 'spotify-24.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvcejycVPCUdHkEjyvk6nexSbgF3VDZ_k',
    appId: '1:520286223732:ios:7bcd95a2f472ded4c10021',
    messagingSenderId: '520286223732',
    projectId: 'spotify-24',
    storageBucket: 'spotify-24.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZzROqtKQQyB-w2gimCuF22AqPojudM2w',
    appId: '1:520286223732:web:fc9d40bbc841f745c10021',
    messagingSenderId: '520286223732',
    projectId: 'spotify-24',
    authDomain: 'spotify-24.firebaseapp.com',
    storageBucket: 'spotify-24.appspot.com',
  );
}
