// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2csQ5_YdRPDbx3iQHfCxmw6oRsVH6se8',
    appId: '1:302623590628:web:e6fe83e6cbd10e013584f1',
    messagingSenderId: '302623590628',
    projectId: 'spotify-app-24-a8d32',
    authDomain: 'spotify-app-24-a8d32.firebaseapp.com',
    storageBucket: 'spotify-app-24-a8d32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgCFdyoXFrXl7_x7iYigENZgbhKhb7BOw',
    appId: '1:302623590628:android:5fc6f33885dc6cbb3584f1',
    messagingSenderId: '302623590628',
    projectId: 'spotify-app-24-a8d32',
    storageBucket: 'spotify-app-24-a8d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtCV6qzJV3KY--u6V5a8Qi2BCvDLVUmA',
    appId: '1:302623590628:ios:08f3c81cf16c61333584f1',
    messagingSenderId: '302623590628',
    projectId: 'spotify-app-24-a8d32',
    storageBucket: 'spotify-app-24-a8d32.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtCV6qzJV3KY--u6V5a8Qi2BCvDLVUmA',
    appId: '1:302623590628:ios:08f3c81cf16c61333584f1',
    messagingSenderId: '302623590628',
    projectId: 'spotify-app-24-a8d32',
    storageBucket: 'spotify-app-24-a8d32.appspot.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2csQ5_YdRPDbx3iQHfCxmw6oRsVH6se8',
    appId: '1:302623590628:web:3c9fbf1008f3eadc3584f1',
    messagingSenderId: '302623590628',
    projectId: 'spotify-app-24-a8d32',
    authDomain: 'spotify-app-24-a8d32.firebaseapp.com',
    storageBucket: 'spotify-app-24-a8d32.appspot.com',
  );
}
